script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-4.0.x
  - Gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: rbx-19mode
      gemfile: gemfiles/Gemfile.rails-4.0.x
